[project]
name = "code-editor"
version = "0.1.0"
description = ""
main_script = "./src/main.py"

[packages]
PyQt5 = "5.15.9"
QScintilla = "2.14.0"

[scripts]
upgrade-pip = "python -m pip install --upgrade pip"
